POST http://localhost:9017/V9/VegGroup/Insert/PkReturn
Content-Type: application/json

{
  "VegGroupName": "",
  "VegGroupImage": "",
  "VegGroupImageExt": "",
  "VegGroupLeftCol": "",
  "VegGroupRightCol": ""
}