POST http://localhost:9017/V7/VegTable/Alter/ColumnsWithPk/{pk}
Content-Type: application/json

{
  "GroupName": "",
  "GroupTelugu": "",
  "VegetableName": "",
  "VegetableImage": "",
  "VegetableTelugu": "",
  "VegetableRate": ""
}