POST http://localhost:9017/V8/VegTable/Insert/PkReturn
Content-Type: application/json

{
  "GroupName": "",
  "GroupTelugu": "",
  "VegetableName": "",
  "VegetableImage": "",
  "VegetableTelugu": "",
  "VegetableRate": ""
}