POST http://localhost:9017/V7/VegTable/Insert/SchemaColumnsOnly
Content-Type: application/json

{
  "GroupName": "",
  "GroupTelugu": "",
  "VegetableName": "",
  "VegetableImage": "",
  "VegetableTelugu": "",
  "VegetableRate": ""
}
