POST http://localhost:9017/V9/VegTable/Alter/WithPk/{pk}
Content-Type: application/json

{
  "GroupFK": "",
  "GroupTelugu": "",
  "VegetableName": "",
  "VegetableImage": "",
  "VegetableTelugu": "",
  "VegetableRate": ""
}